name: "store"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../../store:/workspaces/store:cached

    # プロセス終了後にシャットダウンしないようにデフォルトコマンドを上書きします。
    command: sleep infinity

    # すべてのプロセスで非rootユーザーを使用する場合は、次の行をコメント解除してください。
    # user: vscode

    # アプリのポートをローカルに転送するには、**devcontainer.json** の "forwardPorts" を使用してください。
    # (このファイルに "ports" プロパティを追加しても、Codespaceからは転送されません。)
    depends_on:
    - selenium

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

  
